name: Build e Push para Docker Hub

on:
  push:
    branches: [ "main" ]

env:
  # Optando pelo Node.js 24 conforme recomendado pelo GitHub
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build do Backend
      - name: Build e Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iptu-backend:latest

      # Build do Frontend
      - name: Build e Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iptu-frontend:latest
          build-args: |
            NEXT_PUBLIC_API_URL=https://api-laniptu.geredados.com.br
